name: Fetch Shiller PE Ratio Data

on:
  workflow_dispatch:

jobs:
  fetch-shiller-pe-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Debug repository structure
        run: ls -R
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
      
      - name: Fetch Shiller PE Ratio data
        run: python fetch_shiller_pe_ratio.py
      
      - name: Check if data file exists
        run: |
          if [ -f "shiller_pe_data.csv" ]; then
            echo "File exists..."
          else
            echo "shiller_pe_data.csv not found! Skip commit."
            exit 1
          fi
      
      - name: Commit and push data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add shiller_pe_data.csv
          git commit -m 'Update Shiller PE Ratio data' || echo 'No changes to commit'
          git push
